### ISSUE TITLE
Problem loading module

### ISSUE THREAD

**Issue by melvinhertz** [rkuykendall/marvelous#4]
I get the following error in python 3.4.2 when trying to load the module... any ideas? Package seemed to install OK. I'm a noob.  Trying to run this on a raspberry pi 3. 

Traceback (most recent call last):
  File "/home/pi/myApps/Marvel/marvel.py", line 2, in <module>
    import marvelous
  File "/usr/local/lib/python3.4/dist-packages/marvelous/__init__.py", line 1, in <module>
    from . import session, exceptions
  File "/usr/local/lib/python3.4/dist-packages/marvelous/session.py", line 5, in <module>
    from . import exceptions, comics_list, series
  File "/usr/local/lib/python3.4/dist-packages/marvelous/comics_list.py", line 3, in <module>
    from . import comic, exceptions
  File "/usr/local/lib/python3.4/dist-packages/marvelous/comic.py", line 3, in <module>
    from . import dates, series
  File "/usr/local/lib/python3.4/dist-packages/marvelous/series.py", line 3, in <module>
    from . import comics_list, exceptions
ImportError: cannot import name 'comics_list'

**Comment by rkuykendall** [comment]
Hey @melvinhertz! Hm, I actually do think I see the problem. That looks like a 'circular import'. Funny, since I haven't hit this on my personal computer running my weekly script. I will definitely look into it further as soon as I get off work.

If you're interested in the technical explanation: The imports go `init > session > comics_list > comic > series > ` and then `series` wants to import `comic_list` but then it would continue `comics_list > comic > series > comics_list > comic > series > comics_list > comic > series > comics_list > comic > series > comics_list > comic > series > ...` forever and ever. So instead, it just fails.

**Comment by melvinhertz** [comment]
Awesome, thank you for looking into it and for the technical explanation as well!

**Comment by rkuykendall** [comment]
Hey @melvinhertz! Sorry for the delay. I wasn't able to produce your problem locally, even with a clean install, so that makes this tricky. However, I implemented something that I think might fix it. Could you try installing a new version of the library like below, and let me know if that fixes it?

```pip3 install https://github.com/rkuykendall/marvelous/archive/melvinhertz.zip```

I appreciate your help in fixing this, as I'm sure others encountered the same thing.

**Comment by melvinhertz** [comment]
It worked! Thanks! Awesome! So excited!

Just as an fyi for other noobs like me, I had to append --upgrade at the end to get it to update correctly. (and use sudo, may be because using raspberry pi)

**Comment by rkuykendall** [comment]
Thanks for your help @melvinhertz! I merged the fix and released marvelous v1.0.3. You should be able to use the official version now without any problems. If all is well, I'll close this issue.

**Comment by melvinhertz** [comment]
Anytime! I installed the newest version and it still works, thanks again! Good to close.

**Comment by rkuykendall** [comment]
Awesome! Let me know if there's anything else you'd like to do with the library. It works perfectly fine for all my personal scripts, so I don't currently have any items on my to-do list.
